version: "3.9"
services:
  dev:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
    - 3000:3000
    volumes:
      - ./app:/app
    command: yarn start